#spring.datasource.url=jdbc:mysql://localhost:3306/login_system
#spring.datasource.username=root
#spring.datasource.password=root

# Use sqlite for convenient
spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/data/main.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: info
    com.zzn.librarysystem: debug

spring.devtools.restart.enabled: false

#739829812